/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithholdingRouteImport } from './routes/_app/withholding'
import { Route as AppTfpcRouteImport } from './routes/_app/tfpc'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppIrgRouteImport } from './routes/_app/irg'
import { Route as AppIbsRouteImport } from './routes/_app/ibs'
import { Route as AppG50RouteImport } from './routes/_app/g50'
import { Route as AppExpertRouteImport } from './routes/_app/expert'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithholdingRoute = AppWithholdingRouteImport.update({
  id: '/withholding',
  path: '/withholding',
  getParentRoute: () => AppRoute,
} as any)
const AppTfpcRoute = AppTfpcRouteImport.update({
  id: '/tfpc',
  path: '/tfpc',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIrgRoute = AppIrgRouteImport.update({
  id: '/irg',
  path: '/irg',
  getParentRoute: () => AppRoute,
} as any)
const AppIbsRoute = AppIbsRouteImport.update({
  id: '/ibs',
  path: '/ibs',
  getParentRoute: () => AppRoute,
} as any)
const AppG50Route = AppG50RouteImport.update({
  id: '/g50',
  path: '/g50',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertRoute = AppExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/expert': typeof AppExpertRoute
  '/g50': typeof AppG50Route
  '/ibs': typeof AppIbsRoute
  '/irg': typeof AppIrgRoute
  '/settings': typeof AppSettingsRoute
  '/tfpc': typeof AppTfpcRoute
  '/withholding': typeof AppWithholdingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/expert': typeof AppExpertRoute
  '/g50': typeof AppG50Route
  '/ibs': typeof AppIbsRoute
  '/irg': typeof AppIrgRoute
  '/settings': typeof AppSettingsRoute
  '/tfpc': typeof AppTfpcRoute
  '/withholding': typeof AppWithholdingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expert': typeof AppExpertRoute
  '/_app/g50': typeof AppG50Route
  '/_app/ibs': typeof AppIbsRoute
  '/_app/irg': typeof AppIrgRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tfpc': typeof AppTfpcRoute
  '/_app/withholding': typeof AppWithholdingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/expert'
    | '/g50'
    | '/ibs'
    | '/irg'
    | '/settings'
    | '/tfpc'
    | '/withholding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/expert'
    | '/g50'
    | '/ibs'
    | '/irg'
    | '/settings'
    | '/tfpc'
    | '/withholding'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/expert'
    | '/_app/g50'
    | '/_app/ibs'
    | '/_app/irg'
    | '/_app/settings'
    | '/_app/tfpc'
    | '/_app/withholding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withholding': {
      id: '/_app/withholding'
      path: '/withholding'
      fullPath: '/withholding'
      preLoaderRoute: typeof AppWithholdingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tfpc': {
      id: '/_app/tfpc'
      path: '/tfpc'
      fullPath: '/tfpc'
      preLoaderRoute: typeof AppTfpcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/irg': {
      id: '/_app/irg'
      path: '/irg'
      fullPath: '/irg'
      preLoaderRoute: typeof AppIrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ibs': {
      id: '/_app/ibs'
      path: '/ibs'
      fullPath: '/ibs'
      preLoaderRoute: typeof AppIbsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/g50': {
      id: '/_app/g50'
      path: '/g50'
      fullPath: '/g50'
      preLoaderRoute: typeof AppG50RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expert': {
      id: '/_app/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AppExpertRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpertRoute: typeof AppExpertRoute
  AppG50Route: typeof AppG50Route
  AppIbsRoute: typeof AppIbsRoute
  AppIrgRoute: typeof AppIrgRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTfpcRoute: typeof AppTfpcRoute
  AppWithholdingRoute: typeof AppWithholdingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpertRoute: AppExpertRoute,
  AppG50Route: AppG50Route,
  AppIbsRoute: AppIbsRoute,
  AppIrgRoute: AppIrgRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTfpcRoute: AppTfpcRoute,
  AppWithholdingRoute: AppWithholdingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
